---
services:
  - type: web
    name: shoppit-backend
    runtime: python
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn shoppit.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "false"
      - key: REACT_BASE_URL
        value: "https://myshop-uxr0.onrender.com"