databases:
  - name: shoppit-db
    plan: free
    databaseName: shoppit
    user: shoppit

services:
  - type: web
    name: shoppit-backend
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn shoppit.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: shoppit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: ALLOWED_HOSTS
        value: "*"
      # ‚Üê DEBUG line removed! Handled automatically in settings.py
      - key: REACT_BASE_URL
        value: https://myshop-uxr0.onrender.com